### ISSUE TITLE
ValueError on array with same shape as example

### ISSUE THREAD

**Issue by elligottmc** [MLWave/kepler-mapper#1]
Hi first of all this is a great open source implementation of the Mapper been searching for one.  I am trying to build a complex using some weather data.

My shape:

X.shape

(7477, 2)

Circle example shape:

data.shape

(5000, 2)

Yet I'm getting ValueError: all the input array dimensions except for the concatenation axis must match exactly.

Here's a sample of my data:

X[0]

array([  1.02,  28.  ])

I'm sure I'm doing something silly could you guide me?

**Comment by MLWave** [comment]
```
import km
import numpy as np

data = np.random.random((7477, 2))
print data.shape
print data

# Initialize
mapper = km.KeplerMapper(verbose=1)

# Fit to and transform the data
projected_data = mapper.fit_transform(data, projection=[0, 1])

# Create dictionary called 'complex' with nodes, edges and meta-information
graph = mapper.map(projected_data, data, overlap_perc= 0.4, nr_cubes=20)

# Visualize it
mapper.visualize(graph, path_html="make_data_keplermapper_output.html")


###### OUTPUT

"""
(7477, 2)
[[ 0.39073848  0.62724999]
 [ 0.06854704  0.03010319]
 [ 0.04916002  0.70188549]
 ...,
 [ 0.52910549  0.49338699]
 [ 0.24947786  0.5004319 ]
 [ 0.19567324  0.06012327]]

..Projecting data using: [0, 1]

..Scaling with: MinMaxScaler(copy=True, feature_range=(0, 1))

Mapping on data shaped (7477, 2) using lens shaped (7477, 2)

Creating 400 hypercubes.
Minimal points in hypercube before clustering: 1

created 1444 edges and 400 nodes in 0:00:07.917206.

Wrote d3.js graph to 'make_data_keplermapper_output.html'
"""
```

Is above sample running fine?

**Comment by elligottmc** [comment]
Wow I had forgotten about that it was so long ago.  I managed to input my data successfully but honestly can't recall exactly what I was doing wrong now.  Regardless I still do appreciate the tool and make use of it quite a bit.  My thanks.
