### ISSUE TITLE
visualize in a jupyter notebook?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [MLWave/kepler-mapper#10]
Great SW!  I'm trying to run the code in a `jupyter notebook`, but it doesn't work, i.e. I get the .html file saved but no display in the notebook.

```
from IPython.core.display import display, HTML
...
display(mapper.visualize(graph, path_html="make_circles_keplermapper_output.html", 
                 title="make_circles(n_samples=5000, noise=0.03, factor=0.3)"))
```
I also tried `HTML(mapper.visualize...)` with no result.

Any suggestion?

**Comment by smartinsightsfromdata** [comment]
I ended up using:

```
import IPython
url = 'make_circles_keplermapper_output.html'
iframe = '<iframe src=' + url + ' width=700 height=600></iframe>'
IPython.display.HTML(iframe)
```

And it worked for me.

**Comment by MLWave** [comment]
Thanks for showing a code snippet that works for you. 

I'll make note of this in the documentation somewhere.
