### ISSUE TITLE
Image Tooltips

### ISSUE THREAD

**Issue by leesteinberg** [MLWave/kepler-mapper#100]
Hi Devs

In the `confidence_graphs` notebook, image tooltips are used in the visualisation. This is something which we feel could be very useful in our work here. 

However, when we create our image tooltips in the same way, and follow the procedure outlined in the notebook, we find that rather than get a nice array of images under `MEMBERS` in the output html file, all of our images overlay (essentially, the html tag doesn't seem to be processed correctly).

I assume this is down to a change in the visualization since the notebook was written. I'm not sure this is a browser issue (using Chrome). Are you aware of this, and if so if it is possible to create image tooltips?

Lee

**Comment by sauln** [comment]
This might be an issue with the recent changes.  Have you tried with the pypi release version or with the code on github/master?

**Comment by leesteinberg** [comment]
I'm using the code on github/master

I'm not sure if it is an issue with the pypi release version.

**Comment by MLWave** [comment]
I also tested in Chrome, so unlikely to be a browser issue. I'll make a small example later on and then we can see how to make it work for you.

**Comment by leesteinberg** [comment]
@MLWave any update on this? Consistent image tooltips would be such a useful feature!

**Comment by sauln** [comment]
Hey @leesteinberg, could you try again with the master branch and let me know if it works for you now?

I think the stacking was caused by a change I made when rendering the custom tooltips.  The fix I just merged worked on Chrome and Safari with Python 3.6 for me.

**Comment by leesteinberg** [comment]
Seems to be working now. Much appreciated.
