### ISSUE TITLE
How to plot picture like matplotlib style?

### ISSUE THREAD

**Issue by kidozh** [MLWave/kepler-mapper#106]
I want to plot that picture in an article, however, direct print from browser always have problems.

I also used that way in this issue [https://github.com/MLWave/kepler-mapper/issues/73](https://github.com/MLWave/kepler-mapper/issues/73) but failed.

I am wondering if there is a way to plot picture neatly in article.

Thanks a lot.

**Comment by sauln** [comment]
Have you looked at method described in #96?

The usual method is to use screen shots (cmd shift 4 on mac) with a white background (press `p` key).

**Comment by sauln** [comment]
I've been playing around with using networks for some visualization. There's an adapter [here](https://github.com/MLWave/kepler-mapper/blob/adapter/kmapper/adapter.py) and some scratch visualization code [here](https://github.com/MLWave/kepler-mapper/blob/adapter/kmapper/drawing.py).  

Let me know if something like this is helpful.

**Comment by kidozh** [comment]
Sorry for my delay.

I have seen your branch and found that it may not neat for my condition.
I directly parsed JSON in HTML and used `igraph` to show the network. Histogram is also ploted according to HTML.

Thanks a lot for your reply.

**Comment by sauln** [comment]
Okay, sounds like you have it figured out so I'm going to close out this issue. 

If you'd like to share you solution in more depth, I would love to see how you did it.
