### ISSUE TITLE
Reading/Writing Networks

### ISSUE THREAD

**Issue by leesteinberg** [MLWave/kepler-mapper#107]
Hey Devs,

Often I've figured it may be useful to have a write/read utility for mapper networks produced by KeplerMapper. Is this something being developed? If not, how would you suggest one could be written? I suppose a basic interface with networkX could work, but maybe you reckon there is a better way?

Let me know your thoughts

**Comment by deargle** [comment]
Just pickle the graph metadata? That's what I do.

**Comment by leesteinberg** [comment]
I guess that would work! Should have tried it myself...

**Comment by sauln** [comment]
Interfacing with networks is a fine idea and I have been doing this a lot for personal projects. I've pushed a scratch network adapter [here](https://github.com/MLWave/kepler-mapper/blob/adapter/kmapper/adapter.py). 

Would something along these lines be helpful? Let me know as I'm trying to iron out any use cases and corner cases I haven't thought about.
