### ISSUE TITLE
Mapper long term direction

### ISSUE THREAD

**Issue by sauln** [MLWave/kepler-mapper#11]
I'd like to talk about future directions of kepler-mapper and some work I'd like to do. Before I get too far ahead of myself, I want to make sure you (@MLWave) agree with the directions so a permanent fork won't be necessary.

Immediate steps are 
- [x]  Get kepler-mapper into pypi.
- [x]  Decompose some of the main routines to allow for easier unit testing.

Do you have a vision or direction for kepler-mapper?  There is considerable new research on the method  and I think kepler-mapper would be a great platform to introduce some of these ideas.

* Automatic parameter tuning
* Multiscale mapper
* Automatic feature extraction

**Comment by MLWave** [comment]
I don't have a vision for this. Kepler-Mapper was created as just a personal learning project, but it kind of blew up in popularity.

I'd absolutely love to see the introduction of those 3 ideas. Especially multi-scale mapping (and generating barcodes) would have my interest.

Getting Kepler-mapper onto Pypi and better testing sounds really great. The project deserves a better programmer for this.

I'll give you full edit capabilities, so you can push and pull like you please.

**Comment by sauln** [comment]
I think the disclaimer is fine. I'll keep my eyes out for anything to change.

First off, I think the implementation is great and is a great platform to build off of.  Full disclaimer of myself, I am a graduate student studying Mapper currently. I'd rather not build a new competing tool and instead focus on strengthening the tools that are available. I'm also pretty new to this all though, so it will be a learning process for me.

Paper friendly output of the graph output? That sounds awesome! Have you used Jinja2 before? It might be helpful to use a template engine for the html.

I'm not sure if I'm following how the new ML algorithm would work. I'm interested in learning more. Is there a preliminary writeup? 

My immediate goals are to cut up the main `map` method into a few extra helper objects that provide more customizability:
* **Cover**: an abstraction of the covering scheme. This would implement a method `find_entries` that returns all entries that is in a particular element.  Currently, kepler-mapper only supports cubes. [Multiscale](https://arxiv.org/abs/1504.03763) mapper would require more nuanced control of the cover.
* **Nerve builder**: an abstraction of building the nerve of the clusters. Currently, only edges are built. To implement [multi-nerve mapper](https://arxiv.org/abs/1511.05823) or include higher dimensional simplices, more control over this concept is necessary.

Would either of these objects help the ML algorithm you're thinking of? This is still a work in progress, hopefully in the next few weeks.  In the meantime, I have a growing test suite, some minor bug fixes, and some packaging work to incorporate.

I'm going to submit a new issue for my work on 'packagizing' kepler-mapper. A merge would force some cascading changes to documentation and examples, so feedback would be greatly appreciated!

Thank you,

**Comment by MLWave** [comment]
I'll add the previous version of km.py to the depricated directory, because I forgot about a valuable use-case of KeplerMapper: Use for teaching. Very short, simple, well-documented code (without current concessions for speed/optimization/modularity) can help students understand the mapper algorithm better.
