### ISSUE TITLE
Error kmapper.plotly

### ISSUE THREAD

**Issue by mlnjsh** [MLWave/kepler-mapper#124]
I am running following code 
import kmapper as km
from kmapper.plotlyviz import plotlyviz
from kmapper.plotlyviz import *
import plotly.graphₒbjs as go
import ipywidgets as ipw

giving error

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-24-1e4d9a6241d4> in <module>()
      1 color_function = projected_data[:, 1]-projected_data[:, 1].min()
----> 2 plotlyviz(scomplex, 
      3           title='Mapper graph of digits dataset',
      4           color_function=color_function,
      5           color_functionₙame='Distance to y-min',

NameError: name 'plotlyviz' is not defined

**Comment by empet** [comment]
@mlnjsh  Have you installed the last kmapper version?  Here is the function `plotlyviz`: [https://github.com/MLWave/kepler-mapper/blob/master/kmapper/plotlyviz.py#L57](https://github.com/MLWave/kepler-mapper/blob/master/kmapper/plotlyviz.py#L57).

**Comment by sauln** [comment]
I assume @empet's solution worked and am closing the issue. Please reopen if it is still not working for you. 

The latest version on pypi should work as well.
