### ISSUE TITLE
Parameter "perc_overlap" in Cover class does not seem to actually mean percent overlap

### ISSUE THREAD

**Issue by emerson-escolar** [MLWave/kepler-mapper#125]
**Description**
Meaning of "percent overlap" perc_overlap in Cover class seems to be strange, or imprecisely documented.

Let A and B be two neighboring cubes constructed by the cover class. 
My impression from the [documentation](https://github.com/MLWave/kepler-mapper/wiki/Documentation#Mapping-Data) is that percent overlap should equal:
```
volume(A intersection B) / volume(A)
```
To me, this is the natural meaning of the word "overlap"; i.e. the percentage of the total volume of A that is shared (overlapped) with B. The use of "overlap" in the original Singh et al. Mapper paper also uses this meaning.

Instead it seems that the current algorithm computes the cubes so that perc_overlap is equal to 
```
volume(A intersection B) / volume(A setminus B)
```
for *most* A and B. (the "last" cube is an exception, as seen below).

**To Reproduce**
One way to see what's going on is to use uniformly-spaced input data as a proxy for measuring volume:
```
import numpy as np
from kmapper import cover

# uniform data:
data = np.arange(0,100)
data = data[:,np.newaxis]
lens = data

# divided into 10 bins, with perc_overlap=50%:
cov = cover.Cover(10,0.5)

## imitate usage in kmapper.py KeplerMapper.map:

# Prefix'ing the data with an ID column
ids = np.array([x for x in range(lens.shape[0])])
lens = np.c_[ids, lens]

bins = cov.define_bins(lens)

bins = list(bins)  # extract list from generator
total_bins = len(bins)
print("Creating %s hypercubes." % total_bins)

for i, cube in enumerate(bins):
    hypercube = cov.find_entries(lens,cube)
    print("There are %s points in cube %s/%s" % (hypercube.shape[0], i, total_bins))
    print("members: ", list(hypercube[:,1]))
```
with output (middle lines skipped):
```
Creating 10 hypercubes.
There are 15 points in cube 0/10
members:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
There are 15 points in cube 1/10
members:  [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
...
There are 15 points in cube 8/10
members:  [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94]
There are 10 points in cube 9/10
members:  [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
```
Note that all cubes have 15 members, except the last one, which has only 10.

Then, for example, cube0 and cube1 share 5 members 10,11,12,13,14. This is 
```
volume(cube0 intersection cube1) / volume(cube0)= 5/15 
```
or approximately 33.3% of the total 15 members of cube0,
even though the parameter value was perc_overlap = 50%, which instead is coming from
```
volume(cube0 intersection cube1) / volume(cube0 setminus cube1)= 5/(15-5) = 5/10 = 50%
```

**System details:**
 - OS: macOS Mojave 10.14
 - Python 3.7.0 via Homebrew
 - numpy 1.15.3 from PyPI
 - kepler-mapper installed from source (master, latest commit b7ecd1c)

**Additional comment**
If this is intended behaviour, maybe it should be better documented to avoid confusion?

**Comment by sauln** [comment]
Thank you @emerson-escolar for the detailed report.  I agree that is weird behavior and not what I expected it to do. We'll have to take a more critical look at the Cover algorithm! 

I would expect that the overlap should be calculated as
```
volume(cube0 intersection cube1) / volume(cube0 union cube1)
```

I think the error has to do with how the chunk size is calculated here:

https://github.com/MLWave/kepler-mapper/blob/b7ecd1c573b1da49006aa651313fc2c79293f671/kmapper/cover.py#L101-L105

Each bin should actually be larger, incorporating the overlap into the length of the bin as well.  For instance, if we wanted 2 bins of the unit interval with 50% overlap, the two bins should be `[0,0.75]` and `[0.25, 1]`. Then the intersection would be 0.5 and the union would be 1. 

I'll take a look at it this afternoon for a bit, but if you wanted to submit a PR with a fix/reimplementation for this, it would be greatly appreciated.

**Comment by deargle** [comment]
Just bumped into this also when attempting to force duplicate nodes in test data by specifying 100% overlap and 2 hypercubes on 1d lens :-(

I may try to fix this before finishing the test for the other pr

**Comment by sauln** [comment]
@emerson-escolar, please try out the new cover implementation in master. Not that the API has changed slightly.

**Comment by emerson-escolar** [comment]
Hi @sauln @deargle, thanks very much for working on this. I have tried out the new implementation, and it's working great.
