### ISSUE TITLE
TypeError: map() got an unexpected keyword argument 'perc_overlap'

### ISSUE THREAD

**Issue by karinsasaki** [MLWave/kepler-mapper#126]
I want to change the percent overlap from 0.1 to 0.5.

This is my code:

```
projected_IAVT4 = mapper.fit_transform(IAVT4, distance_matrix='cosine',  projection='dist_mean')

graph_IAVT4 = mapper.map(projected_IAVT4, nr_cubes=10, perc_overlap=0.5)

mapper.visualize(graph_IAVT4, path_html="coinfections_IAVT4.html", title="IAVT4")
```

This is the error I get:

`TypeError: map() got an unexpected keyword argument 'perc_overlap'`

I do not get this when I do not try to specify perc_overlap.

I am not sure what the problem is - any help would be appreciated!

**Comment by karinsasaki** [comment]
I've realised that the parameter name is `overlap_perc` but in the documentation it is listed as `per_overlap`.

**Comment by sauln** [comment]
Hi @karinsasaki, sorry for the confusion.  Where were you reading in the documentation to use `perc_overlap`?  

I believe there is some confusion as we've been encouraging users to make use of the `Cover` object rather than pass the grid parameters directly to `map`.  The parameter in `overlap_perc` is still usable in the map method so as not to break backwards compatibility.

**Comment by karinsasaki** [comment]
Hello @sauln (sorry for the late reply...)

> Where were you reading in the documentation to use `perc_overlap`?
I am following this documentation: https://github.com/MLWave/kepler-mapper/wiki/Documentation# 
If use:
`graph = mapper.map(projected_data, data, nr_cubes=3, overlap_perc=0.7)`
it works, but if I use (as in the documentation above):
`graph = mapper.map(projected_data, data, nr_cubes=3, perc_overlap=0.7)`
it gives me the error:
`map() got an unexpected keyword argument 'perc_overlap'`

> ...we've been encouraging users to make use of the `Cover` object rather than pass the grid parameters directly to `map`.
Can you tell me where I can find the documentation to learn to use the 'Cover' object? I can't seem to find it in the documentation in the link above.

THanks!

**Comment by sauln** [comment]
Sorry for the confusion.  `overlap_perc` argument of `map` is a deprecated API.  I'll get the wiki cleaned up asap.
