### ISSUE TITLE
Color_function implementation

### ISSUE THREAD

**Issue by raunaak** [MLWave/kepler-mapper#127]
Hi,

Looking through one of the advanced tutorials [https://kepler-mapper.scikit-tda.org/TOR-XGB-TDA.html], I found color function was given two choices 0 or 1. But, the map produced has so many colors. Could you please explain this behavior?
Specifically,
`df["label"] = df["label"].map({"nonTOR": 0, "TOR": 1})`
`y = np.array(df.label)`
`_ = mapper.visualize(
    G,
    custom_tooltips=y,
    color_function=y,
    path_html="tor-tda.html",
    inverse_X=X,
    inverse_X_names=list(df[features].columns),
    projected_X=lens,
    projected_X_names=["IsolationForest", "KNN-distance 5"],
    title="Detecting encrypted Tor Traffic with Isolation Forest and Nearest Neighbor Distance"
)`

**Comment by sauln** [comment]
Maybe you're seeing that some examples were computed using a different color palette?

Providing a custom color palette is very close to being supported, but my attention has been on other projects.  Thanks to @empet and their plotlyviz work, custom palettes are available, but not exposed to the D3 UI yet.  If you'd like more robust coloring system, I would suggest trying the new plotlyviz functionality.
