### ISSUE TITLE
`graph['meta_nodes']` incorrect and never used

### ISSUE THREAD

**Issue by deargle** [MLWave/kepler-mapper#128]
**Describe the bug**
`graph['meta_nodes']` is built in a loop [here](https://github.com/MLWave/kepler-mapper/blob/b7ecd1c573b1da49006aa651313fc2c79293f671/kmapper/kmapper.py#L498). But this property:
* is never referenced anywhere else in the repo
* incorrectly sets the cluster "size" to be the size of the hypercube instead of the size of the cluster.

Potential remedies:
* delete all references to this `meta` object in that loop
* change the size calculation to be:

```
meta[cluster_id] = {
    "size": len(nodes[cluster_id])
    "coordinates": cube,
}
```

... because currently the size is set to the number of items in the hypercube, which is incorrect, since clusters are subsets of hypercubes.

I can PR for either remedies if you'd like.

**Comment by sauln** [comment]
You're right, this structure is a little strange. I think this was intended to provide information about the hypercubes, but was largely ignored in past refactoring. 

I do think having some data about hypercubes would be useful.  What that looks like though, I'm not sure. At the very least, the logic should be taken out of that loop so it doesn't get reset every observation.

What are your thoughts? I am open to any PR you think would improve it.

**Comment by deargle** [comment]
The cover refactor refactor removed the cluster coordinate and size meta, closing
