### ISSUE TITLE
Remove duplicate nodes

### ISSUE THREAD

**Issue by deargle** [MLWave/kepler-mapper#129]
It is theoretically possible that several clusters have exactly the same item-sets. Currently, if this happens, duplicate nodes will be drawn, and edges will be drawn between these nodes. For my application where I am interested in node membership instead of just the overall shape or some summary measure of a value of items in a node, duplicate nodes are a distraction.

Open to a PR where duplicate nodes are removed before edges are determined? I don't see this addressed in the original specification of the mapper algo, but I don't see how it could _hurt_ things.

**Comment by sauln** [comment]
I’ve run across situations where this would be helpful as well.

I’m hesitant to change the default behavior, but how about adding it with a flag to trigger?  Otherwise, an extra function that will remove the nodes and edges from the graph after its computed would work fine.

**Comment by deargle** [comment]
I added it as a flag to `.map`. I left a built-in `asset` in there, which in hindsight is tacky and should be in a test suite...

**Comment by sauln** [comment]
Thank you! I've looked over the code and have a few things to 

Could you please 
- [ ] extract this into a helper function like:
```
def _remove_duplicate_nodes(self, nodes):
    ...
   return deduplicated_nodes
```

- [ ] and add tests to ensure it is working correctly.
- [ ] Also, it looks like it could be converted to use list comprehension style. If possible, I'd prefer this method instead of the c style list building.

**Comment by deargle** [comment]
- [x]  extracted to a helper function
   although I left the name as "nodes" because of the popping
- [x] added a test
   although I left the `assert` in the helper function because it's not readily apparent to me how to know externally whether there will be any nodes to remove
- [x] list-comprehensioned the creation of the list of popped ids
   although I did not list-comprehension-ize the upper-left-triangle nested loops because my head would have exploded and I think the readability would have cried

Look good?

**Comment by sauln** [comment]
You should be able to create fake input to the function for a test. Otherwise, it’s not clear that the function works at all.

Please remove the internal asserts.
