### ISSUE TITLE
AttributeError: type object 'Cover' has no attribute 'MultiScaleCubical'

### ISSUE THREAD

**Issue by karinsasaki** [MLWave/kepler-mapper#135]
**Describe the bug**
The [documentation](https://github.com/MLWave/kepler-mapper/wiki/Documentation) says that, using the attribute MultiScaleCubical of Cover, you can use multiple and different cubes per projection dimension and also vary the overlap. But when I run:

`cover=km.cover.MultiScaleCubical(n_cubes=[10,20,5],perc_overlap=[0.1,0.2,0.5]))`

or

`cover=km.Cover.MultiScaleCubical(n_cubes=[10,20,5],perc_overlap=[0.1,0.2,0.5]))`

(notice the change from 'cover' to 'Cover')

It gives me the error:

`AttributeError: type object 'Cover' has no attribute 'MultiScaleCubical'`

**Comment by sauln** [comment]
Hi, Sorry the wiki documentation is a little off and still a work in progress. Please take a look at the official documentation here: [kepler-mapper.scikit-tda.org](https://kepler-mapper.scikit-tda.org).

The API for varying overlap and cubes along each dimension is actually supported in the default Cover api. 

Using 
```
cover=km.cover.Cover(n_cubes=[10,20,5],perc_overlap=[0.1,0.2,0.5]))
```

should work just fine.

**Comment by karinsasaki** [comment]
ok, thanks!
