### ISSUE TITLE
Strange behaviour of the scaler

### ISSUE THREAD

**Issue by karinsasaki** [MLWave/kepler-mapper#136]
I sample data from a circle with the following function (which is a specialisation of the make_circles function from sklearn):

```
from sklearn import utils
def make_circle(n_samples=100, shuffle=False, noise=None, random_state=None, n_labels=2):
    """
    Make a doughnut in 3d.
    
    Parameters
    ----------
    n_samples : int, optional (default=100)
        The total number of points generated. If odd, the inner circle will
        have one point more than the outer circle.
    shuffle : bool, optional (default=True)
        Whether to shuffle the samples.
    noise : double or None (default=None)
        Standard deviation of Gaussian noise added to the data.
    random_state : int, RandomState instance or None (default)
        Determines random number generation for dataset shuffling and noise.
        Pass an int for reproducible output across multiple function calls.
        See :term:`Glossary <random_state>`.
    n_labels : number of distinct labels for class membership of each sample
    Returns
    -------
    X : array of shape [n_samples, 2]
        The generated samples.
    y : array of shape [n_samples]
        The integer labels for class membership of each sample.
    """
    
    generator = utils.check_random_state(random_state)
    
    # so as not to have the first point = last point, we set endpoint=False
    linspace = np.linspace(0, 2 * np.pi, n_samples, endpoint=False)
    circ_x = np.cos(linspace)
    circ_y = np.sin(linspace)
    circ_z = np.zeros(n_samples)
    
    X = np.vstack([circ_x, circ_y, circ_z]).T
    y = np.sort(np.random.randint(low=1, high=n_labels+1, size=n_samples, dtype=np.intp))
    
    if shuffle:
        X, y = util_shuffle(X, y, random_state=generator)

    if noise is not None:
        X += generator.normal(scale=noise, size=X.shape)

    return X, y
```

Sample data:

```
circle, labels = make_circle(n_samples=20, shuffle=False, noise=0.1, random_state=1, n_labels=5)
```

I transform the data using sklearn.preprocessing.MinMaxScaler:

```
min_max_scaler = sklearn.preprocessing.MinMaxScaler()
transformed_circle = min_max_scaler.fit_transform(circle)
```

and I create a custom lens from the transformed data using sklearn.manifold.Isomap:

```
lens_isomap = sklearn.manifold.Isomap(n_components=3, n_neighbors=5).fit_transform(transformed_circle)
```

I also create a lens from the original data using the fit_transform method from mapper:

```
lens_isomap_mapper = mapper.fit_transform(circle, projection=sklearn.manifold.Isomap(n_components=3, n_neighbors=5), scaler=MinMaxScaler())
```

As I understand, I should get the same values for the two lenses, since in fit_project the scaler of the data is applied before mapping - but this is not the case, as shown in the images. (If I create the lens using fit_transform on the scaled data with scaler=None then I get the same as the Costume lens, as expected.)

Custom lens:
![custom_lens](https://user-images.githubusercontent.com/18656780/53177606-a2b98080-35f0-11e9-88dd-f0e453968ef0.png)

fit_transform lens:
![fit_transform](https://user-images.githubusercontent.com/18656780/53177610-a2b98080-35f0-11e9-9117-78422517f204.png)

I do not know if this points to a bug in the mapper and how it may affect analysis down the line.

**Comment by sauln** [comment]
The `mapper.fit_transform` method will apply the projection and then apply the scaling to the projection. In the example you provided, you are computing the scaling, and then projecting that.  

Are they the same if you switch the order?

**Comment by karinsasaki** [comment]
I see. Yes, when I apply the scaler after mapping then I get the same - thanks.

You might like to change the documentation in the kmapper.py, because it says that the scaler is applied **before** mapping (see image).

![screen shot 2019-02-22 at 10 17 39](https://user-images.githubusercontent.com/18656780/53232476-7141c300-368b-11e9-9083-f0b4ddb6a9fd.png)

**Comment by sauln** [comment]
Glad that works. If you’d like to submit a PR for this doc update, it would be a great first issue to handle.

**Comment by karinsasaki** [comment]
I've submitted a PR request for this!
