### ISSUE TITLE
'list' object has no attribute 'fit_transform' when running "make_circles" example

### ISSUE THREAD

**Issue by drmingle** [MLWave/kepler-mapper#2]
---

AttributeError                            Traceback (most recent call last)
<ipython-input-16-934e94845567> in <module>()
      9 
     10 # Fit to and transform the data
---> 11 projected_data = mapper.fit_transform(data, projection=[0,1]) # X-Y axis
     12 
     13 # Create dictionary called 'complex' with nodes, edges and meta-information

C:\Users\admin\Anaconda3\lib\km.py in fit_transform(self, X, projection, scaler)
     62           pass
     63         print("\n..Projecting data using: \n\t%s\n"%str(projection))
---> 64       X = reducer.fit_transform(X)
     65 
     66     # Detect if projection is a string (for standard functions)

AttributeError: 'list' object has no attribute 'fit_transform'

**Comment by natbusa** [comment]
+1

**Comment by jsevo** [comment]
+1

**Comment by mlnjsh** [comment]
where to see visualization output

**Comment by mlnjsh** [comment]
.Projecting data using: 
	PCA(copy=True, n_components=None, whiten=False)


..Scaling with: MinMaxScaler(copy=True, feature_range=(0, 1))

Mapping on data shaped (5000, 2) using dimensions

Creating 1000 hypercubes.

created 92 edges and 58 nodes in 0:00:03.084211.

Wrote d3.js graph to 'make_circles_keplermapper_output.html'


AFTER Above i dont see any ouput please guide

​

**Comment by mlnjsh** [comment]
****

**Comment by tuomastik** [comment]
@mlnjsh 
> where to see visualization output

Open the file `make_circles_keplermapper_output.html` in your web browser.

**Comment by MLWave** [comment]
I think this was due to buggy class detection in Python 3+.

Pushed a new version today that does this differently. Can anyone tell me if this problem persists?

**Comment by sauln** [comment]
I added a test that confirms the issue with projecting onto particular dimensions is resolved.
