### ISSUE TITLE
Incorporate all relevant information into "meta_graph"

### ISSUE THREAD

**Issue by sauln** [MLWave/kepler-mapper#20]
All information about the constructed graph should be stored in `graph["meta_graph"]`.  The `visualize` method should use attributes in this dictionary rather than found from `self`.

This would allow us to separate the construction of the visualization from the construction of the graph object alone.  Additionally, the graph could be saved with all of its relevant information and graphed at a later time.

What is the best way to assimilate information from both fit_transform and map? Maybe fit_transform sets what it can and then map included this information also?

**Comment by MLWave** [comment]
One problem I could see is if people specify custom lenses/projections. I think it should be possible to map a projection without creating a projection through KeplerMapper. Right now, this breaks the meta information (for instance the visualization requires knowledge of the projection used). Perhaps API can be more flexible to this / allow better ways for users to specify this meta information / should gracefully deal with missing information from custom projections.

**Comment by sauln** [comment]
Yes! I think currently, the visualization says "custom" for type of lens if fit_transform hasn't been run before. Maybe it would be better to just not include the information in the visualization if it's not present?  

If the meta data about the projection is in graph["meta_graph"] rather than attached to the mapper object, it might be more natural for a user to add extra information. 

I haven't dug too deep into the visualize method, so this could be more complicated than I expect.
