### ISSUE TITLE
Add Travis-CI to project.

### ISSUE THREAD

**Issue by sauln** [MLWave/kepler-mapper#22]
By integrating CI, Travis will automatically run the test suite before any pull request. 

I've added the .travis.yml settings file and tested everything so it works on my fork. From what I can tell, only the owner of the repo can integrate travis into the repo. 

@MLWave, when you have a second, could you turn this on? It took me <3 minutes on my fork, just follow the first few steps [here](https://github.com/dwyl/learn-travis). 

Once this is done, we can 
- [x] Add the [build passing badge](https://docs.travis-ci.com/user/status-images/) to the README
- [x] Incorporate other tools to the repo: 
   - [pep8speaks](https://github.com/OrkoHunter/pep8speaks)
- [x] Add codecov

**Comment by MLWave** [comment]
I'll have a look at this over the weekend. Really want to add this, but need some study first.

**Comment by MLWave** [comment]
It seems it is working, but the Py 2.7 build is failing with error. Probably due to `setup.py` containing: 
 `python_requires='>=3'`. I'm ok with subpar 2.7 support, since the libraries that Kepler-Mapper depends on (such as NumPy) plan to drop support starting 2019.

What do we do, add 2.7 to `setup.py` or remove 2.7 from CI?

**Comment by sauln** [comment]
Sorry, I forgot to merge my most recent updates. I'll merge the branch in a second.

**Comment by sauln** [comment]
:100: build is passing now.  One of the tests would fail without 3.5+ order preserving dictionaries, and there is official support for 2.7. At least as far as the tests passing.

Thanks for setting this up!

**Comment by sauln** [comment]
Sorry for another ask.. When you have a minute could you install pep8speaks into the repo to:
https://github.com/apps/pep8-speaks/installations/new

It might also be worthwhile setting up `codecov`.

**Comment by MLWave** [comment]
PEP8 speaks active on this repo.

I'll have a look at `codecov`.

**Comment by MLWave** [comment]
Codecov activated for this repo, but not sure if I need to do anything else. Codecov needs to speak with Travis-CI?

**Comment by sauln** [comment]
Codecov seems considerably more difficult.. I'm having trouble getting travis to initiate a code coverage report. It should just be a small hook in the travis.yml that initiates the codecov, but nothing seems to be activating and I don't see any errors.

**Comment by sauln** [comment]
It looks like the codecov report worked on the last pull request I made. Hopefully it keeps working. :100:

**Comment by sauln** [comment]
It looks like PEP8Speaks is not working properly right now.

**Comment by MLWave** [comment]
Just tested this here and got a response: https://github.com/MLWave/kepler-mapper/pull/31

**Comment by sauln** [comment]
Great! Did you make any changes, or am I just doing it wrong?

**Comment by MLWave** [comment]
Did not make any changes.

It should recognize changes in all .py files for everyone who makes a pull request right?

Perhaps make a test pull to see if it works for you now.
