### ISSUE TITLE
Digits example appears to be using a different version of km

### ISSUE THREAD

**Issue by ekorman** [MLWave/kepler-mapper#4]
For example, the version of km that ``digits.py`` uses assumes that the ``KeplerMapper`` class has a ``reducer`` attribute.  In ``km.py`` given in the repository, this parameter is in the ``fit_transform`` method and is called ``projection``.  Also  ``digits.py`` uses the parameter name ``cluster_algorithm`` instead of ``clusterer`` (as it is in ``km.py``).

**Comment by MLWave** [comment]
Thanks for catching this! I'll update the documentation.

**Comment by ekorman** [comment]
Related, even running ```digits.py``` using the v00004 version of ```km.py```, I'm unable to replicate your results-- the complex I get has just 9 nodes and is connected.  Is it possible scikit-learn's ```DBSCAN``` or ```t-SNE``` have changed since your initial run of ```digits.py```?

**Comment by MLWave** [comment]
Could be, but should not make that much a difference. Thanks, I'll redo this in one go. ETA 2-3 days.

See here for a reproducible version, courtesy of Kaggle Kernels: https://www.kaggle.com/triskelion/mapping-digits-with-a-t-sne-lens

**Comment by MLWave** [comment]
Sorry for taking a while (and the outdated documentation in the first place). I've updated the example for the latest version of Kepler-mapper.

Thanks!

**Comment by ekorman** [comment]
Thanks for the update!  Interestingly I'm having the same problem where I'm getting a simplicial complex with very few nodes but when I try this on two other computers everything works perfectly.  So there must be something weird with the setup on my one computer, though I reinstalled scikit-learn and updated python so I'm not sure what the problem could be.  Just wondering if this happens to be something you have run into before.  Attached is a screenshot.
![screen_shot](https://user-images.githubusercontent.com/9574559/28756917-dae2a48e-753d-11e7-8745-55cd9be81bd7.jpeg)
