### ISSUE TITLE
Get KeplerMapper on Kaggle Kernels

### ISSUE THREAD

**Issue by MLWave** [MLWave/kepler-mapper#40]
The process: https://github.com/Kaggle/docker-python

Some examples already:
https://inclass.kaggle.com/triskelion/mapping-with-sum-row/notebook
https://www.kaggle.com/triskelion/testing-python-3/notebook
https://www.kaggle.com/triskelion/isomap-all-the-digits-2

If we get the new containers to build with kmapper, we can use KeplerMapper on all Kaggle's datasets and use their notebooks for replication/easy forks.

![img](http://i.imgur.com/ItWhCHA.png)

**Comment by sauln** [comment]
Kaggle/docker-python has merged.
