### ISSUE TITLE
Python, HTML & Javascript separation

### ISSUE THREAD

**Issue by smangham** [MLWave/kepler-mapper#44]
I'd like to make some tweaks to the output web page, but as it stands that's slightly awkward to do; the HTML is contained within the Python as a string and so is the JS. It's particularly a problem as I'm doing these changes for someone with less programming experience who might have a hard time resolving any conflicts that could arise trying to keep a fork up-to-date. 

Would splitting them out into separate files that are then read in by the Python and used to produce the finished HTML be a problem? Or potentially just setting them up as Jinja2 templates and rendering them that way? It would make the HTML/Javascript a bit neater by replacing all the %s markers with actual variable names. I could try either, but would prefer not to spend time on it if it's incompatible with the project design somehow!

**Comment by sauln** [comment]
Yes! @Mlwave and I have talked about this before, and it is definitely on the to-do list.

>Or potentially just setting them up as Jinja2 templates and rendering them that way? 
I would prefer this. Do you want to prototype an implementation the Jinja2 templating?

I would recommend starting on the `dev` branch as @MLWave has done a bunch of recent work to the visualizations. 

@MLWave, do you think the `dev` branch is ready to go for this?

**Comment by smangham** [comment]
It was a pretty quick change so I went ahead and gave it a shot.

**Comment by MLWave** [comment]
This all looks very cool, thanks for this!

I did a little bit of work locally on dev branch, but I prefer to work in this templating system, so after this is ready to go, I'll add these changes to the respective new files.

**Comment by sauln** [comment]
Everything is merged into the dev branch now! Thanks for your help and initiative @smangham.
