### ISSUE TITLE
Linking issues with JS/CSS on dev

### ISSUE THREAD

**Issue by smangham** [MLWave/kepler-mapper#48]
The switch to using links to the JS/CSS rather than folding it into the file directly has unfortunately introduced some portability & sustainability issues.

It makes the saved HTML files dependent on the install directory of the module, and any environment used whilst running it- making redistributing them difficult. In addition, the HTML version is static whilst the JS/CSS is linked, potentially leading to old HTML files becoming unusable if the JS/CSS they depend on changes to require tags or elements not present in the old HTML.

**Comment by sauln** [comment]
Thank you for catching this!
