### ISSUE TITLE
dict_to_json bug

### ISSUE THREAD

**Issue by smangham** [MLWave/kepler-mapper#54]
There's a bug in dict_to_json that prevents linking from the json data back to node data. 
The json for a given node is defined as `"name": "node_id"` when it should actually be `"name": node_id`. I've made a quick fix.

**Comment by sauln** [comment]
Thanks for this catch!

Do you think there is a unit test that could have caught this? I don't think we have any tests that probe the visualization functionality.

**Comment by MLWave** [comment]
It took a while, but I've seen the beauty of tests now. I'll work to get global - and especially visualization coverage up.

And thanks!
