### ISSUE TITLE
Examples display error messages  when they are ran

### ISSUE THREAD

**Issue by empet** [MLWave/kepler-mapper#65]
Hi kepler-mapper team,

Thank you very much for your great TDA tool!

Could you  please update the examples in the `keppler-mapper` repo, according to the last version of kmapper?

I ran `digits.py` and got this error message:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-1ae2740795d8> in <module>()
     51                  path_html="keplermapper_digits_custom_tooltips.html",
     52                  graph_gravity=0.25,
---> 53                  custom_tooltips=tooltip_s) 
     54 # Tooltips with the target y-labels for every cluster member
     55 mapper.visualize(graph,

TypeError: visualize() got an unexpected keyword argument 'graph_gravity'
```

I checked the `visualize()` method definition, and indeed it has no keyword `'graph_gravity'`.
I commented it out and it worked, but I noticed that although in your code
the `visualize()` is called with the default value, `None`, for the `color_function`
the node colors in my html file are different from  those of nodes in your html file posted in the folder examples (my  nodes have mostly the central colors in the jet colormap, and only a few are red).
It's obvious that your plot was generated with a special `color_function` that is not set in `digits.py`.
I'd like to know a method of node coloring in the case of a filter function with values in $\mathbb{R}^2$.
All references on TDA, related to mapper algorithm, explain only how to color the  nodes in the case of  a filter function with real values.

For `breast-cancer` example you provided the  `color_function="average_signal_cluster"`, but the `color_function` value should be a `numpy.array` of floats
and this string caused the error:

```
./visuals.py in init_color_function(graph, color_function)
     13         color_function = np.arange(n_samples).reshape(-1, 1)
     14     else:
---> 15         color_function = color_function.reshape(-1, 1)
     16     # MinMax Scaling to be friendly to non-scaled input.
     17     scaler = preprocessing.MinMaxScaler()

AttributeError: 'str' object has no attribute 'reshape'
```

Thanks!!!  :)

**Comment by MLWave** [comment]
Thanks for these issues.

- I'll re-add `graph_gravity` and others to the new visualizations.
- I'll update the documentation & examples
- The older color function default was: distance to `.min()` of first dimension of `projected_X`. The new color function colors by row order of `inverse_X`. I think I liked the older default better.
- `average_signal_cluster` was deprecated, and just passing the target labels to the `color_function` should do much of the same.
- If your filter function output is 2D, you have to somehow turn this into a 1D output. So you will always lose information.
- The hard way to solve for above: split nodes in half and allow halves to be colored with two different colors (hard), the pragmatic way is allowing a 2D (n,m) array where n is number of rows and m are the different color function outputs. Then you can select these from a dropdown menu in the visualization. I'll begin work on this very soon. Something like:

```
html = mapper.visualize(graph, color_function=[[0,1],[2,3]], color_function_names=["target", "age"])
```

**Comment by sauln** [comment]
All examples are up to date and running now in master.
