### ISSUE TITLE
Error KeplerMapper Newsgroup20 Pipeline

### ISSUE THREAD

**Issue by rintrah** [MLWave/kepler-mapper#69]
Dear all, 

Many thanks for Kepler Mapper.  It is a very interesting project.

I have looked at the examples at the notebook folder.  I have found a problem with the notebook  KeplerMapper Newsgroup20 Pipeline.ipynb.  I get the following error when I tried to run the line "projected_X = mapper.fit_transform(X,  projection=[TfidfVectorizer(analyzer="char",                             ngram_range=(1,6), max_df=0.83, min_df=0.05), TruncatedSVD(n_components=100,                        random_state=1729), Isomap(n_components=2, n_jobs=-1)] : 

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-5ac99241f928> in <module>()
     10                 Isomap(n_components=2,
     11                        n_jobs=-1)],
---> 12     scaler=[None, None, MinMaxScaler()])
     13 
     14 print("SHAPE",projected_X.shape)

~/kepler-mapper/kmapper/kmapper.py in fit_transform(self, X, projection, scaler, distance_matrix)
    219             if self.verbose > 0:
    220                 print("\n..Projecting data using: %s" % (str(projection)))
--> 221             X = X[:, np.array(projection)]
    222 
    223         # Scaling

IndexError: arrays used as indices must be of integer (or boolean) type

I have tried different ways to solve the problem, but without any success.  I wonder whether it would be possible for you to suggest me some possible solutions?   

Many thanks for considering my request.

Best wishes

**Comment by sauln** [comment]
Hi, I'm glad you're trying the new features out.  

How did you install kmapper?  The version currently in pypi does not have the pipeline feature that is in the notebook yet, as it's still brand new.  

I'm hoping that if you install the library directly from source, then you shouldn't have any problem running the notebook.

Please let us know if this works for you.

**Comment by rintrah** [comment]
Dear Sauln, 

Thank you for your reply.  

I installed kmapper directly from source the first time.  Nevertheless, I uninstalled and remove the kmapper folder and  reinstalled kmapper directly from source and it worked like a charm.  I should have done this before other tests.  My apologies. 

Many thanks for your help.

Best wishes.

**Comment by sauln** [comment]
Great! glad it's working for you.
