### ISSUE TITLE
Examples out of date

### ISSUE THREAD

**Issue by sauln** [MLWave/kepler-mapper#7]
After the API changes of v00008 some of the examples have not been updated.

These include
* Cat
* Horse
* Lion

**Comment by sauln** [comment]
I've started converting the mentioned examples, but the new results are uninteresting.  You can find the current output sauln@79d215c5900bed4a54e022dbfb2049055512615b

Do you have any suggestions for making the results look more like the old style?

**Comment by MLWave** [comment]
Thanks for reporting. This is in the backlog.

**Comment by sauln** [comment]
If you could provide direction, I would be happy to put in the grunt work of updating them.  I've started the update but have not been able to replicate the output from the old versions.

**Comment by MLWave** [comment]
I'll do one and put it here. Rest should follow from that. Thanks!

**Comment by sauln** [comment]
It looks like the issue was not with tuning the mapper like I originally thought.  Instead there was a small bug in the way the simplicial complex was constructed.  I submitted a pull request with the fix.  With the fix in place, the examples fall readily into place.

**Comment by sauln** [comment]
With pull request #8, the examples fall into place and look fine. I'll create a new pull request with the updated examples once #8 is integrated.

**Comment by MLWave** [comment]
Thanks again!
