### ISSUE TITLE
Same error although installed from source

### ISSUE THREAD

**Issue by Maurizio-sanarico-sdg** [MLWave/kepler-mapper#70]
Hi, I installed KeplerMapper from source and running the newsgroup notebook I still got the same error as that in the recently closed issue. Is there something wrong? Thank you for the wonderful work and dedication.
mapper = km.KeplerMapper(verbose=2)

projected_X = mapper.fit_transform(X,
    projection=[TfidfVectorizer(analyzer="char",
                                ngram_range=(1,6),
                                max_df=0.83,
                                min_df=0.05),
                TruncatedSVD(n_components=100,
                             random_state=1729),
                Isomap(n_components=2,
                       n_jobs=-1)],
    scaler=[None, None, MinMaxScaler()])

print("SHAPE",projected_X.shape)

..Projecting data using: [TfidfVectorizer(analyzer='char', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.83, max_features=None, min_df=0.05,
        ngram_range=(1, 6), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None), TruncatedSVD(algorithm='randomized', n_components=100, n_iter=5,
       random_state=1729, tol=0.0), Isomap(eigen_solver='auto', max_iter=None, n_components=2, n_jobs=-1,
    n_neighbors=5, neighbors_algorithm='auto', path_method='auto', tol=0)]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-3a323e834380> in <module>()
     10                 Isomap(n_components=2,
     11                        n_jobs=-1)],
---> 12     scaler=[None, None, MinMaxScaler()])
     13 
     14 print("SHAPE",projected_X.shape)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\kmapper\kmapper.py in fit_transform(self, X, projection, scaler, distance_matrix)
    219             if self.verbose > 0:
    220                 print("\n..Projecting data using: %s" % (str(projection)))
--> 221             X = X[:, np.array(projection)]
    222 
    223         # Scaling

IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by empet** [comment]
It seems that you kept the older version 1.1.3 installed usually, with pip, too. That's why the same error persists. If this is the case, uninstall it with  `pip uninstall kmapper`

`pip  install -e`  installed kmapper  into the current working directory (`kepler-mapper`). Hence you should run the notebook from that  folder and it will work. 

I experienced the same issue and this was the way I fixed it.

**Comment by sauln** [comment]
Thanks for helping @empet. 

There should be a way to install it from source without needing to run from that folder.  I don't have much experience with conda, but maybe using `conda install -e .`?  I always install it this way into a `virtualenv`.

**Comment by Maurizio-sanarico-sdg** [comment]
Thank you all for the suggestions, actually conda is good for many things, but, on the other side, it is complicating the, to me not so linear way Python has to manage folders. Unfortunately, Kepler Mapper that is, according to me, the best open source implementation of Mapper, it is not in the Conda repositories, so you have either to use pip. However, I didn't try to use conda install when installing from source, so I'll give a try and if successful I'll provide a feeedback. Again thank you

**Comment by sauln** [comment]
Great. Let us know how it works. I'll look into getting Kepler Mapper into the conda repositories so some of these issues.

**Comment by Maurizio-sanarico-sdg** [comment]
On the next few days I'll try to fix it and I'll inform you about the results. Thank you

**Comment by Maurizio-sanarico-sdg** [comment]
At the end I had to remove the virtual environment in which I installed Kmapper, after uninstalling kapper. I used the command rmvirtualenv, from virtualenvwrapper. Then, I reinstalled kmapper and now it is working properly.
