### ISSUE TITLE
Breast cancer example

### ISSUE THREAD

**Issue by mlnjsh** [MLWave/kepler-mapper#81]
In Breast cancer example you are using the following code lines 

 **We create a custom 1-D lens with Isolation Forest**
model = ensemble.IsolationForest(random_state=1729)
model.fit(X)
lens1 = model.decision_function(X).reshape((X.shape[0], 1))

My question is .. What does this lense1 is doing i mean what kind of projection do we have ? are we projecting our data on predictions of isolation forest...I am not sure please help????

**Comment by sauln** [comment]
Maybe looking at the [documentation for isolation forest](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.IsolationForest.html) would help your understanding?

Isolation forests don't make predictions, they compute anomaly scores for each observation in `X`.
> The anomaly score of an input sample is computed as the mean anomaly score of the trees in the forest.
