### ISSUE TITLE
Enable precomputed similarity matrices for clustering

### ISSUE THREAD

**Issue by deargle** [MLWave/kepler-mapper#88]
Hi, I just opened PR #87. Context is that I had a precomputed distance matrix that I wanted to cluster with. I used T-SNE to scale it down to two dimensions for the filter function, but I didn't see a way to use `metric='precomputed'` with DBSCAN for the clustering with `inverse_X` because of the hypercube slicing making things un-square. So this PR is what I did to tell mapper to give a square matrix to the clusterer.

**Comment by sauln** [comment]
Thanks for working on this! 

The distance matrix stuff hadn't been working for a while.  Once the unit tests are passing and there are some new ones in place, I'll merge this is in.

**Comment by sauln** [comment]
#87 has been merged. Thank you!
