### ISSUE TITLE
Issues using HDBSCAN

### ISSUE THREAD

**Issue by leesteinberg** [MLWave/kepler-mapper#91]
Hi there,

When using HDBSCAN (from hdbscan library, as suggested in Issue #68), the code terminates with :
`ValueError: k must be less than or equal to the number of training points`

This is with the default behaviour (i.e. using `mapper.map(projected_X=projected_data, inverse_X=data, clusterer=hdbscan.HDBSCAN()`)

The same data and projection work fine with `DBSCAN()`, so I assume its an issue with the interaction with `hdbscan`. Maybe you know something about this?

**Comment by sauln** [comment]
`HDBSCAN` has a parameter `min_cluster_size` that I believe eventually gets passed down to other functions under the name `k`.  The default for this is 5. It's possible that the cover element that is being passed to `HDBSCAN` has less than 5 and then the clusterer is balking.

I just added some code to the master branch that will only try to cluster data that is larger than `min_cluster_size`. We had something similar for K-means clustering also.

Could you try installing from the library from master and see if that fixes the problem for you?

```
git clone https://github.com/mlwave/kepler-mapper
cd kepler-mapper
pip install -e .
```

**Comment by leesteinberg** [comment]
This seems to work now - thanks.

I think there might be issues with the visualizer on master - particularly with IE (which is not surprising). Unfortunately, I am very restricted to using IE - is it safe to use an old version of `visuals.py` (the version of the library on pip seemed to work)?

**Comment by leesteinberg** [comment]
I've made a pull request modifying `_format_tooltip`

`perc_overlap` can be set > 1. Is there a reason why someone might want to do this?

**Comment by sauln** [comment]
Hi @leesteinberg, the PR looks good. I'll merge it as soon as I have time to actually run the code.

The way the bin width is calculated is a little confusing at first.  The amount of percentage of overlap is calculated as a percentage of the distance between bins, not the percent the bins overlap. If it was actual overlap, then we could never have finite bin length and `perc_overlap==1`.  

Suppose you wanted the bins to interact with bins that are not directly adjacent.  Maybe the little drawing below helps.

![drawing](https://user-images.githubusercontent.com/5808961/40733295-171dbf9c-63ea-11e8-8954-8010c2df0017.png)
