### ISSUE TITLE
Statistical Analysis of Nodes in Graph

### ISSUE THREAD

**Issue by mlnjsh** [MLWave/kepler-mapper#93]
Hi, I am extremely sorry , If I am Asking some simple questions.

As I am Mathematician by profession and Not the programmer..

I would like to know 

1. How to perform statistical analysis on any of the node in mapper graph?
2. Is there any way to grey out the unwanted nodes and display relevant nodes in the graph?
3. Can we search any important information regarding any variable (s) that are in the clusters as a node in the mapper graph?
4. is there any way to extract all the attributes associated to mapper graph

I would highly appreciate, If you respond ...

**Comment by sauln** [comment]
Hi @mlnjsh, thanks for your questions.

Many of the features you ask for, we don't have built into the visualizations.  Once you construct a mapper and visualize it, the `Cluster Details` pane can give you membership information for each node when you hover over it.  If you'd like to further analyze certain nodes, you can copy these member ids back into Python and look at the associated subset of data.

Does this help?

**Comment by mlnjsh** [comment]
Thank'u so much , I will think upon this answer..Find out the way..
In my visualization I see only Mapper graph there is no pane as such _Cluster Details_
I don't know m i using older version  ..
is there any way to upgrade it 
thanku for Response

**Comment by leesteinberg** [comment]
*Not one of the developers, but:*
If you install the version directly from source you can get the cluster details pane (From what I can tell, it isn't on the pip version)
`git clone https://github.com/mlwave/kepler-mapper`
`cd kepler-mapper`
`pip install -e . `
**NB:** the arguments of the `KeplerMapper.map()` method have also changed.
`projected_X --> lens`
`inverse_X --> data`

*If any of the above is wrong, devs, please let me know!*

**Comment by sauln** [comment]
Thanks @leesteinberg for fielding this!  That's all correct.  

Before the way of showing member info was passing in the custom tooltip. I just set it up so the default tooltip was member indices so it's a little easier to use out of the box.

I tried pretty hard to make all my changes backwards compatible, so using `projected_X` instead of `lens` should still work.  Please let me know if this is not the case!

**Comment by mlnjsh** [comment]
Thanks dev and user...
Now i m in right direction ..thanku for help
