### ISSUE TITLE
How to download the plot with white background?

### ISSUE THREAD

**Issue by doerlbh** [MLWave/kepler-mapper#96]
Hi, thanks for providing the great software for TDA!

I am looking for a way to download the TDA plot with white background to use and cite it in a research paper, is there a way to extract it as a clean and high-resolution plot, other than the current option to download the html with black background?

Thanks!

**Comment by doerlbh** [comment]
#

**Comment by marcoswastaken** [comment]
I'm also interested in a way to save the visualization (or a good approximation) as something friendly for including as a figure in a paper or report.

**Comment by sauln** [comment]
In the past, I just used screenshots to capture a png of the plot. Will this not work for you? Are you thinking something like an `export as png` button on the visualization?

The pull request #74 has an way of displaying the network using plotly. It's not completely merged right now, but if you can get that working, it will have ways of exporting the network.  I'm planning on integrating the PR, but will probably be a while before it's ready.

**Comment by doerlbh** [comment]
Thanks, sauln. Yes, I am currently  using screenshot to extract the image (after changing the html to my need). However, it would be great to have "export as png" option (preferably in white background). I will check out the pull request #74 and plotly you mentioned.

BTW, is there a way to change the node size in display? 

Have a great day.

**Comment by MLWave** [comment]
This is my fault (UI design).

You can use shortcuts for this:

```
[p] = "print mode"
[d] = "display mode"

[s] = "Christmas mode: the nodes light up/glow"
[c] = "Sober mode: the nodes are solid"

[m] = "Moon mode: The graph has less gravity"
[e] = "Earth mode: The graph looks normal"
[z] = "Zero gravity mode: Weird stuff"
```

Press "m" or "z" followed by "e" to sort of reset the graph. This results in a graph that sometimes looks nicer than the graph that is produced by random init. Then use "p" and "s" followed by "c" to get the most print-worthy graph for screenshots.

But this was documented. It also does not work on all browsers (I only tested in Chrome, and know that Safari fails).

**Comment by sauln** [comment]
@doerlbh There's no built in way of changing the node size.  Pull requests are very welcome.

@mlwave pointed out those keyboard shortcuts.  If you are using the development version that is currently on github master branch, the help menu provides some of this information. 

I'm not sure that 'export as png' button would give you better facilities than using the 'p' key with a screenshot.  Is it still necessary?
